# Generated by Django 5.1.5 on 2025-01-22 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
